@startuml

interface Decoder

Decoder : numpy.array decode()

class TextDecoder implements Decoder

class TextFileDecoder extends TextDecoder


interface Detector

Detector : float: score(invader: Decoder, shingle: Shingle)

class SimpleDetector implements Detector

class Shingle {
        Tuple[int, int] : row_index_range
        Tuple[int, int] col_index_range
        numpy.array : contents
        Any : empty_value
}

interface Renderer

Renderer : render(screen: Decoder, detections: List[numpy.array])

class StandardOutputRenderer implements Renderer

class Tracker

Tracker : List[numpy.array] track_invaders()

class App

App : run()

App --* Tracker
App --* Renderer

Tracker --* "many" Decoder
Tracker --* Detector
Tracker --* "many" Shingle

@enduml